version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
