name: 'Gradle Wrapper Upgrade'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  upgrade-gradle-wrapper:
    runs-on: ubuntu-latest
    env:
      WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.WRAPPER_UPGRADE_GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.email "StefMaDev@outlook.com"
          git config --global user.name "StefMa"
          git config --global url."https://unused-username:${WRAPPER_UPGRADE_GIT_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Upgrade Gradle Wrapper
        run: ./gradlew upgradeGradleWrapperAll